title: Example Pup Quiz
display_question_numbers: false
revealjs_path: reveal.js/
custom_css: |
  .reveal ol { list-style-type: upper-alpha; }
  .answer { color: red }
  .source {
      font-size: x-small;
  }
  .source::before {
      content: "Source: ";
  }
  #question_number {
      position: absolute;
      top: 5%;
      left: 5%;
      font-family: var(--r-main-font);
      font-size: var( --r-heading3-size);
      font-weight: normal;
      color: var(--r-main-color);
  }
