name: Lint YAML files

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get yamllint version
        run: yamllint --version

      - name: Lint yaml files
        run: yamllint quiz
